---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: demo-node-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: demo-node-app
    spec:
      containers:
      - name: {{ .Chart.Name }}
        # image: roskad.jfrog.io/demonode-docker-prod-local/demo-node-app:${APP_VERSION}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
      imagePullSecrets:
      # - name: regcred
      - name: {{ .Values.imagePullSecrets.name }}
