---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: demo-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: {{ .Values.service.type }}