JFROG_PLATFORM_URL="" 
JFROG_PLATFORM_ACCESS_TOKEN=""

JFROG_PROJECT_NAME=""

REPO_NAME_LIST=["",""]

## default
JAS_ENABLED=true
VULN_CONTEXTUAL_ANALYSIS_STATUS=true
EXP_SCAN_SECRETS_STATUS=true
EXP_SCAN_IAC_STATUS=true
EXP_SCAN_SERVICES_STATUS=true
EXP_SCAN_APPLICATIONS_STATUS=true
XRAY_SCAN_DATA_RETENTION_DAYS=180