apiVersion: v1
kind: Service
metadata:
  name: demo-node-app-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: demo-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-node-app-deployment
spec:
  selector:
    matchLabels:
      app: demo-node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-node-app
    spec:
      containers:
      - name: demo-node-app
        image: roskad.jfrog.io/demonode-docker-prod-local/demo-node-app:${APP_VERSION}
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
